version: '3.3'

services:
  bot:
    container_name: "${BOT_CONTAINER_NAME}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "app/${BOT_NAME}"
    volumes:
    - .:app/logs
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
